### PR TITLE
Polar coordinate utils

### PR DESCRIPTION
**Pull request by slackmage**
A handy geometric conversion when doing gaming stuffs involving angles. Not sure whether this should go in the geom or conversion package.

Returning an array for the polar coord since there is existing class for it, but one can be easily made - just wasn't sure what opinions might be on util methods that require a in import for their return values.

### CODE REVIEW

**Comment by mimshwright** [comment]
That's cool. Seems like it would be even better if it returned a PolarPoint (?) object instead of an Array. I dunno if that conflicts with our guidelines or not. You could add that later if you like.

**Comment by slackmage** [comment]
I had thought about making a class for the return but ultimately I think its just import and structure clutter for the end user. I think they should make the decision as to how the represent the resulting data.

If and when we determine guidelines for returning non base objects (whether its ok or not) I can always update. Most people are just going to copy the code out of the method and put it in their own anyways ;)

Thanks for taking care of that merge mims.

**Comment by mimshwright** [comment]
Looks like your tests aren't passing. Mind giving it a look?

**Comment by slackmage** [comment]
Sure. I'll give it a look in the morning.

**Comment by slackmage** [comment]
Hey Mims, fix is in.

BTW where did the contribution docs get off to? The old link is broken. Should probably enforce that tests end in "Test" rather than something like "Tests" so we're consistent.

**Comment by mimshwright** [comment]
I submitted a pull request for the docs but it looks like I may be the
only one merging lately.

Mims H. Wright
http://mimswright.com
Note: thid mwssage was typed witg my thumbs on thr iPhone.

On May 2, 2011, at 14:23, ianmclean
reply@reply.github.com
wrote:

**Comment by slackmage** [comment]
I'll merge it once I'm home. If you're moderating why not just commit directly?

**Comment by mimshwright** [comment]
Since there are so many committers, I think it would be best if people have at least one other person look at their code to make sure it all makes sense and everything. I wrote it into the commit guidelines and figured I should follow my own rules. I'm going to go ahead and do a cherry pick merge of those docs though.

**Comment by slackmage** [comment]
I went ahead and merged them a day or so ago.

**Pull request merged**
